meta_title: "Coderz: The Software Marketplace"
meta_description: "The Version Control Marketplace with AI Commits For Managing, Deploying, Buying, And Selling Apps"
meta_image: "logo.png"
twitter_account: "@gitlocker"
